version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  Beforeinstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/strat_server
      timeout: 300
      runas: root